config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.

  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                            to: 'home#index'
    resources :products,          only: :show
    resources :categories,        only: :show
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    devise_for :users, {
      class_name: "Spree::User",
      controllers: {
             unlocks: "users/unlocks",
            sessions: "users/sessions",
           passwords: "users/passwords",
       registrations: "users/registrations",
       confirmations: "users/confirmations",
      },
      path_names: {
        sign_in: "login",
        sign_out: "logout"
      },
    }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :prms, only: :show
  before_action :define_params_names, only: :show
  before_action :select_active_btn, only: :show
  helper_method :prm_value, :prm_key, :other_prm

  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(:root)
    @option_types = Spree::OptionType.includes(:option_values).all
    @products_or_variants = products_or_variants(param: @params_name, taxon: @taxon)
    @grid_params = link_params("grid")
    @list_params = link_params("list")
  end

  def define_params_names
    @params_name = params_name
    @another_params_name = another_param_name
  end

  def params_name
    prm_key judge_param_name(param_sym: :size, another_param_sym: :color)
  end

  def another_param_name
    prm_key judge_param_name(param_sym: :color, another_param_sym: :size)
  end

  private

  def link_params(type)
    hash = {}
    active_params(hash: hash, key: :source, val: type)
    active_params(hash: hash, key: @params_name, val: prm_value(@params_name))
    active_params(hash: hash, key: @another_params_name, val: prm_value(@another_params_name))
    hash
  end

  def active_params(args)
    args[:hash].store(args[:key], args[:val].to_sym) unless args[:val].nil?
  end

  def select_active_btn
    @grid = @list = nil
    if params[:source] == "grid" || params[:source].nil?
      @grid = "active"
    elsif params[:source] == "list"
      @list = "active"
    end
  end

  def other_prm(args)
    args[:variant].option_values.where.not(presentation: args[:prm_value]).first.presentation
  end

  def judge_param_name(args)
    if param_nil?(:color) && param_nil?(:size)
      nil
    elsif param_nil?(:color)
      args[:param_sym]
    elsif param_nil?(:size)
      args[:another_param_sym]
    end
  end

  def products_or_variants(args)
    if param_nil?(args[:param])
      select_taxon_products(args)
    else
      select_variants(args[:param])
    end
  end

  def select_taxon_products(args)
    Spree::Product.find_taxon_products(args)
  end

  def select_variants(prm_value)
    Spree::Variant.joins(:option_values).
      where("spree_option_values.presentation":
      :"#{prm_value(prm_value)}").includes(:product)
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  BAGS_CATEGORY_ID = 3
  MUGS_CATEGORY_ID = 4
  SHIRTS_CATEGORY_ID = 6

  def index
    category_ids = [SHIRTS_CATEGORY_ID, BAGS_CATEGORY_ID, MUGS_CATEGORY_ID]
    @categories = Spree::Taxon.arrange_hot_categories_by(category_ids)
    @latest_products = Spree::Product.includes_master.order(available_on: :desc)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  # before_action :authenticate_potepan_user!
  RELATED_PRODUCTS_NUMBERS = 4

  def show
    @product = select_products(params[:id])
    @variant = Spree::Variant.find_by_color(params[:color])
    @main_images = select_images(product: @product, variant: @variant)
    @related_products = Spree::Product.find_related_products(@product).
      limit(RELATED_PRODUCTS_NUMBERS)
    @prior_url = prior_url(@product)
  end

  def select_images(args)
    if params[:color].nil?
      default_images(args)
    else
      color_images(args)
    end
  end

  def select_products(param)
    if params[:color].nil?
      product(param)
    else
      variant_products(param)
    end
  end

  private

  def product(param)
    Spree::Product.find(param)
  end

  def variant_products(param)
    Spree::Product.joins_option_values(param)
  end

  def color_images(args)
    args[:product].variant_images.find_color_images(args)
  end

  def default_images(args)
    args[:product].images
  end

  def prior_url(product)
    if request.referrer.nil? || !request.referrer.include?("/categories/")
      potepan_category_path(product.taxons.first.root.id)
    else
      request.referrer
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  layout "sample"
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/views/potepan/products/_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag product.display_image.attachment.url(:product) %>
      <%= render "potepan/shared/product_masking" %>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path product.id do %>
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <%= render partial: "product", collection: @related_products %>
</div>

app/views/potepan/products/_single_products.html.erb
<div class="row singleProduct">
  <div class="col-xs-12">
    <div class="media">
      <div class="media-left productSlider">
        <div id="carousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% images.each_with_index do |image, i| %>
              <div class="item<%= " active" if i == 0 %>" data-thumb="<%= i %>">
                <%= image_tag(image.attachment.url(:large)) %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="clearfix">
          <div id="thumbcarousel" class="carousel slide" data-interval="false">
            <div class="carousel-inner">
              <% images.each_with_index do |image, i| %>
                <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
                  <%= image_tag(image.attachment.url(:small)) %>
                </div>
              <% end %>
            </div>
            <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          </div>
        </div>
      </div>
      <div class="media-body">
        <ul class="list-inline">
          <li>
            <%= link_to @prior_url do %>
              <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-plus" aria-hidden="true"></i>Share This
            <% end %>
          </li>
        </ul>
        <h2><%= product.name %></h2>
        <h3><%= product.display_price %></h3>
        <p><%= product.description %></p>
        <span class="quick-drop">
          <select name="guiest_id3" id="guiest_id3" class="select-drop">
            <option value="0">S</option>
            <option value="1">M</option>
            <option value="2">L</option>
            <option value="3">XL</option>
          </select>
        </span>
        <span class="quick-drop resizeWidth">
          <select name="guiest_id4" id="guiest_id4" class="select-drop">
            <option value="0">1 pc</option>
            <option value="1">2 pcs</option>
            <option value="2">3 pcs</option>
            <option value="3">4 pcs</option>
          </select>
        </span>
        <span class="quick-drop resizeWidth">
          <select name="guiest_id5" id="guiest_id5" class="select-drop">
            <option value="0">Black</option>
            <option value="1">Red</option>
            <option value="2">Green</option>
            <option value="3">Blue</option>
          </select>
        </span>
        <div class="btn-area">
          <%= link_to "#", class: "btn btn-primary btn-block" do %>
            カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
          <% end %>
        </div>
        <div class="tabArea">
          <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#details">details</a></li>
            <li><a data-toggle="tab" href="#about-art">about art</a></li>
            <li><a data-toggle="tab" href="#material">material</a></li>
            <li><a data-toggle="tab" href="#size">size</a></li>
          </ul>
          <div class="tab-content">
            <div id="details" class="tab-pane fade in active">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua.</p>
              <ul class="list-unstyled">
                <li>Black, Crew Neck</li>
                <li>75% Cotton, 25% Rayon</li>
                <li>Waterbased Ink</li>
                <li>Wash Cold, dry low</li>
              </ul>
            </div>
            <div id="about-art" class="tab-pane fade">
              <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis
                condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit vitae
                dignissim volutpat. </p>
            </div>
            <div id="sizing" class="tab-pane fade">
              <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam varius
                cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo facilisis, pulvinar
                convallis nunc.</p>
            </div>
            <div id="shipping" class="tab-pane fade">
              <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut ullamcorper. Cras
                at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu congue metus. Aenean eros
                tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<!-- LIGHT SECTION -->
<%= render "potepan/shared/light_section", name: @product.name %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <%= render "single_products", product: @product, images: @main_images %>
    <%= render "related_products", related_products: @related_products %>
  </div>
</section>