config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.

  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root                            to: 'home#index'
    resources :products,          only: :show
    resources :categories,        only: :show
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    devise_for :users, {
      class_name: "Spree::User",
      controllers: {
             unlocks: "users/unlocks",
            sessions: "users/sessions",
           passwords: "users/passwords",
       registrations: "users/registrations",
       confirmations: "users/confirmations",
      },
      path_names: {
        sign_in: "login",
        sign_out: "logout"
      },
    }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_copyright.html.erb
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by
          <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
          <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BRANDS</h5>
          <ul class="list-unstyled">
            <li><a href="#">Barbour </a></li>
            <li><a href="#">Brioni </a></li>
            <li><a href="#">Oliver Spencer</a></li>
            <li><a href="#">Belstaff</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Get in Touch</h5>
          <ul class="list-unstyled">
            <li>Call us at (555)-555-5555</li>
            <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="newsletter clearfix">
          <h4>Newsletter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2">go
              <i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title><%= make_title(yield(:title)) %></title>

<%= csrf_meta_tags %>
<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', media: "all" %>

<!-- CUSTOM CSS -->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<!--[endif]-->

app/views/layouts/_header_loginned.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li>
              <span>
                <%= link_to "Logout", destroy_potepan_user_session_path %>
              </span>
            </li>
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">検索</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i>¥0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>ショッピングカート</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X 199円</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X 199円</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default" onclick="#">カートを見る</button>
                    <button type="button" class="btn btn-default" onclick="location.href='checkout_step_1.html';">購入する</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="javascript:void(0)"><%= image_tag("logo.png") %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><%= link_to "Home", potepan_root_path %></li>
          <li class="dropdown megaDropMenu">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>レディース</li>
                  <li><a href="#">トップス</a></li>
                  <li><a href="#">アウター</a></li>
                  <li><a href="#">ボトムス</a></li>
                  <li><a href="#">靴</a></li>
                  <!-- <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li> -->
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <!-- <li>Products List View</li>
                  <li><a href="product-list-left-sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li> -->
                  <li class="listHeading">メンズ</li>
                  <li><a href="#">トップス</a></li>
                  <li><a href="#">アウター</a></li>
                  <li><a href="#">ボトムス</a></li>
                  <li><a href="#">靴</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>キッズ</li>
                  <li><a href="#">トップス</a></li>
                  <li><a href="#">アウター</a></li>
                  <li><a href="#">ボトムス</a></li>
                  <li><a href="#">靴</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>アクセサリー</li>
                  <li><a href="#">モバイルケース・アクセサリー</a></li>
                  <li><a href="#">財布・革小物</a></li>
                  <li><a href="#">腕時計</a></li>
                  <li><a href="#">帽子</a></li>
                </ul>
                <!--   <a href="#" class="menu-photo"><img src="img/menu-photo.jpg" alt="menu-img"></a> -->
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About
              US</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li><a href="#">About Us</a></li>
              <!-- <li><a href="signup.html">Register</a></li>
              <li><a href="signup-login.html">Register or Login</a></li>
              <li><a href="login.html">Login</a></li> -->
              <!-- <li><a href="lost-password.html">Password Recovery</a></li> -->
              <li><a href="#">Privacy Policy</a></li>
              <!-- <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li> -->
              <!-- <li><a href="404.html">404 Not Found</a></li> -->
              <!--                     <li><a href="coming-soon.html">Coming Soon</a></li>    -->
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <!-- <li><a href="blog-right-sidebar.html">Right Sidebar</a></li> -->
              <li><a href="#">Left Sidebar</a></li>
              <!-- <li><a href="blog-fullwidth.html">Full Width</a></li>
              <li><a href="blog-single-fullwidth.html">Single Post</a></li>
              <li><a href="blog-single-right-sidebar.html">Single Right Sidebar</a></li> -->
              <li><a href="#">Single Left Sidebar</a></li>
            </ul>
          </li>
          <!--  <li class="dropdown">
             <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
             <ul class="dropdown-menu dropdown-menu-right">
               <li><a href="account-dashboard.html">Dashboard</a></li>
               <li><a href="account-profile.html">Profile</a></li>
               <li><a href="account-all-orders.html">All Orders</a></li>
               <li><a href="account-single-order.html">Single Order</a></li>
               <li><a href="account-wishlist.html">Wishlist</a></li>
               <li><a href="account-address.html">Address</a></li>
             </ul>
           </li> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_header_not_loginned.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li>
              <span>
                <%= link_to "Log in", "#login", data: {toggle: "modal"} %>
                <small>or</small>
                <%= link_to "Create an account", "#signup", data: {toggle: "modal"} %>
              </span>
            </li>
            <li class="dropdown searchBox">
              <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
                <i class="fa fa-search"></i>
              <% end %>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <%= text_field :search, class: "form-control", placeholder: "Search...", :"aria-describedby" => "basic-addon2" %>
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>$0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to potepan_root_path, class: "navbar-brand" do %>
          <%= image_tag("img/logo.png") %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_root_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li><a href="#">Products Sidebar Left</a></li>
                  <li><a href="#">Products Sidebar Right</a></li>
                  <li><a href="#">Products 3 Columns V1</a></li>
                  <li><a href="#">Products 3 Columns V2</a></li>
                  <li><a href="#">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li><a href="#">Products Sidebar Left</a></li>
                  <li><a href="#">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li class="active"><a href="#">Single Product</a></li>
                  <li><a href="#">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="#">Step 1 - Address</a></li>
                  <li><a href="#">Step 2 - Shipping</a></li>
                  <li><a href="#">Step 3 - Payment</a></li>
                  <li><a href="#">Step 4 - Payment</a></li>
                  <li><a href="#">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li><a href="#">About Us</a></li>
              <li><a href="#">Register</a></li>
              <li><a href="#">Register or Login</a></li>
              <li><a href="#">Login</a></li>
              <li><a href="#">Password Recovery</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Terms &amp; Conditions</a></li>
              <li><a href="#">404 Not Found</a></li>
              <li><a href="#">Coming Soon</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="#">Right Sidebar</a></li>
              <li><a href="#">Left Sidebar</a></li>
              <li><a href="#">Full Width</a></li>
              <li><a href="#">Single Post</a></li>
              <li><a href="#">Single Right Sidebar</a></li>
              <li><a href="#">Single Left Sidebar</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My
              Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="#">Dashboard</a></li>
              <li><a href="#">Profile</a></li>
              <li><a href="#">All Orders</a></li>
              <li><a href="#">Single Order</a></li>
              <li><a href="#">Wishlist</a></li>
              <li><a href="#">Address</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">LOGIN</h3>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: potepan_user_session_path) do |f| %>
          <div class="form-group">
            <%= f.label :"login-email", "Enter Email" %>
            <%= f.email_field :email, class: "form-control", id: "login-email",
                              autofocus: true, autocomplete: "email" %>
          </div>

          <div class="form-group">
          <%= f.label :"login-password", "Password" %>
            <%= f.password_field :password, class: "form-control", id: "login-email",
                                 autocomplete: "current-password" %>
          </div>

          <% if devise_mapping.rememberable? -%>
            <div class="checkbox">
              <%= f.label :remember_me do %>
                <%= f.check_box :remember_me %>
                <span>Remember Me</span>
              <% end %>
            </div>
          <% end -%>

          <%= f.submit "Login", class: "btn btn-primary btn-block" %>
        <% end %>
          <%= button_tag "Forgot Password?", class: "btn btn-link btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_product_quick_view_modal.html.erb
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("img/products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>$149</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle
              support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
                  <select name="guiest_id3" id="guiest_id3" class="select-drop">
                    <option value="0">Size</option>
                    <option value="1">Size 1</option>
                    <option value="2">Size 2</option>
                    <option value="3">Size 3</option>
                  </select>
                </span>
            <span class="quick-drop resizeWidth">
                  <select name="guiest_id4" id="guiest_id4" class="select-drop">
                    <option value="0">Qty</option>
                    <option value="1">Qty 1</option>
                    <option value="2">Qty 2</option>
                    <option value="3">Qty 3</option>
                  </select>
                </span>
            <div class="btn-area">
              <a href="#" class="btn btn-primary btn-block">Add to cart
                <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sign_up_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: potepan_user_registration_path, method: :post) do |f| %>
          <%= devise_error_messages! %>

          <div class="form-group">
            <%= f.label :"signup-email", "Email" %>
            <%= f.email_field :email, class: "form-control", id: "signup-email", autofocus: true, autocomplete: "email" %>
          </div>

          <div class="form-group">
            <%= f.label :"signup-password", "Password" %>
            <% if @minimum_password_length %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %>
            <%= f.password_field :password, class: "form-control", id: "signup-password", autocomplete: "new-password" %>
          </div>

          <div class="form-group">
            <%= f.label :"signup-password-confirmation", "Password Confirmation" %>
            <%= f.password_field :password_confirmation, class: "form-control", id: "signup-password-confirmation", autocomplete: "new-password" %>
          </div>

          <div class="actions">
            <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render "layouts/head" %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>
  <div class="main-wrapper">
    <% if potepan_user_signed_in? %>
      <%= render "layouts/header_loginned" %>
    <% else %>
      <%= render "layouts/header_not_loginned" %>
    <% end %>

    <%= yield %>

    <%= render "layouts/footer" %>
    <%= render "layouts/copyright" %>
  </div>

  <%= render "layouts/login_modal" %>
  <%= render "layouts/sign_up_modal" %>
  <%= render "layouts/product_quick_view_modal" %>

  <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/sample.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potepanec</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>